### PR TITLE
Upgraded dynamic model creation sample

### PR DESCRIPTION
**Pull request by mgernand**
... to Microsoft.AspNet.OData 6.1.0 and Microsoft.OData.Core 7.4.1.

The sample now works with the latest OData version. 

Fixes: #65 
Relates to: #50

### CODE REVIEW

**Comment by xuzhg** [comment]
@mgernand It seems out build system doesn't support the v4.7 version. See error message "The reference assemblies for framework ".NETFramework,Version=v4.7" were not found."

**Comment by mgernand** [comment]
@xuzhg Well, then I suggest you update the build system. ;-)

**Comment by xuzhg** [comment]
@mgernand Updating the build system is not easy because the build system is also for other product.
Is there any reason why you have to use v4.7?

**Comment by xuzhg** [comment]
@mgernand Thank for your PR. We created the similar projects based on your PR. Thanks a lot.

**Pull request closed without merging**
